r"""Techno-economics (screening level) with user-entered local prices; default currency INR, switchable.

Per kg H2 from Al: :math:`n_{Al}=n_{H_2}/1.5` (8.92 kg Al and, if aluminate is discarded, 13.2 kg NaOH per kg H2;
``naoh_recovery`` credits NaOH regenerated by gibbsite precipitation). Costs: consumables + by-product credit +
capital recovery (CRF) of stack/reactor/battery + O&M. Results per kg H2, per kWh (electric at the drive) and per km.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from ..constants import MW_AL, MW_ALOH4, MW_H2, MW_NAOH
from ..core.params import ParamSet
from ..optimize.cost import Prices, al_price
from ..thermo import propdb as DB
from .sizing import LABEL, ScaleUpResult, VehicleSpec, size_system

H2_MOL_PER_KG = 1.0 / MW_H2  # mol/kg


@dataclass
class Economics:
    label: str
    currency: str
    cost_per_kg_h2: float
    cost_per_kWh_el: float
    cost_per_km: float
    breakdown_per_kg_h2: dict[str, float]
    al_kg_per_kg_h2: float
    naoh_kg_per_kg_h2: float
    petrol_cost_per_km: float
    grid_ev_cost_per_km: float
    capex_total: float


def crf(rate: float, years: float) -> float:
    """Capital recovery factor."""
    return rate / (1.0 - (1.0 + rate) ** -years) if rate > 0 else 1.0 / years


def kg_per_kg_h2(form_yield: float = 1.0, naoh_excess: float = 1.0, naoh_recovery: float = 0.0) -> tuple[float, float]:
    """(kg Al, kg NaOH) consumed per kg H2 (stoichiometry, 1 Al : 1 NaOH, 1.5 H2 per Al)."""
    n_al = H2_MOL_PER_KG / 1.5 / form_yield
    return n_al * MW_AL, n_al * naoh_excess * (1.0 - naoh_recovery) * MW_NAOH


def techno_economics(sc: ScaleUpResult | None = None, prices: Prices | None = None, p: ParamSet | None = None, form: str = "can",
                     v: VehicleSpec | None = None, naoh_recovery: float = 0.0, aluminate_credit: bool = True, years: float = 5.0,
                     rate: float = 0.12, hours_per_year: float = 500.0, om_fraction: float = 0.05, currency: str | None = None,
                     n_cells: int = 4) -> Economics:
    """Cost per kg H2, per kWh and per km. ``currency`` converts the INR-denominated user prices with the user-set FX table."""
    p, prices = p or ParamSet(), prices or Prices()
    v = (v or VehicleSpec()).filled(p)
    sc = sc or size_system(v, p, n_cells)
    cur = currency or prices.currency
    fx = prices.fx[cur]
    al_kg, naoh_kg = kg_per_kg_h2(p["al_yield"], p["naoh_excess"], naoh_recovery)
    al_cost = al_kg * al_price(form, prices)
    naoh_cost = naoh_kg * prices.naoh_per_kg
    water_cost = (sc.masses_kg["water"] / sc.h2_kg) * prices.water_per_L
    credit = 0.0
    if aluminate_credit:
        # reusable aluminate/hydroxide mass per kg H2 (as NaAl(OH)4 or equivalent Al(OH)3 mass)
        credit = (H2_MOL_PER_KG / 1.5) * MW_ALOH4 * prices.na_aluminate_credit_per_kg
    capex = (sc.masses_kg["stack"] / p["stack_mass_per_cell"]) * prices.cell_cost + sc.reactor_L * prices.vessel_per_L
    annual_kg_h2 = sc.h2_kg / (sc.assumptions["t_hours"]) * hours_per_year
    cap_per_kg = capex * crf(rate, years) / max(annual_kg_h2, 1e-12)  # magic: floor
    om = capex * om_fraction / max(annual_kg_h2, 1e-12)  # magic: floor
    per_kg = al_cost + naoh_cost + water_cost - credit + cap_per_kg + om
    kwh_per_kg = sc.energy_electric_Wh / 1e3 / sc.h2_kg
    per_kwh = per_kg / kwh_per_kg
    per_km = per_kwh * sc.energy_Wh_per_km / 1e3
    petrol_km = (sc.comparison["petrol"]["litres"] / v.range_km) * prices.petrol_per_L
    grid_km = (sc.comparison["battery"]["Wh_installed"] * p["batt_dod"] / p["batt_eta_rt"] / 1e3 / v.range_km) * prices.grid_per_kWh
    grid_km = sc.energy_Wh_per_km / 1e3 / p["batt_eta_rt"] * prices.grid_per_kWh
    br = {"aluminium": al_cost, "NaOH": naoh_cost, "water": water_cost, "by_product_credit": -credit, "capital": cap_per_kg, "O&M": om}
    return Economics(LABEL, cur, per_kg * fx, per_kwh * fx, per_km * fx, {k: x * fx for k, x in br.items()}, al_kg, naoh_kg,
                     petrol_km * fx, grid_km * fx, capex * fx)


def sensitivity_al_price(prices: Prices, factors: tuple[float, ...] = (0.5, 1.0, 2.0), form: str = "can", **kw: object) -> list[tuple[float, float]]:
    """Cost per kg H2 versus the Al price multiplier (screening what dominates)."""
    out = []
    for f in factors:
        pr = prices.model_copy(update={f"al_{'scrap_can' if form == 'can' else form}_per_kg": getattr(prices, f"al_{'scrap_can' if form == 'can' else form}_per_kg") * f})
        out.append((f, techno_economics(prices=pr, form=form, **kw).cost_per_kg_h2))  # type: ignore[arg-type]
    return out


_ = (math, DB)
