e("ec_E0_Al", -2.328, "V vs SHE", -2.5, -2.1, 0.02, cat="electrochem", src="[SRC-EC1] Al(OH)4-/Al standard potential", status="unverified", desc="Standard potential of Al + 4OH- = Al(OH)4- + 3e- (25 C)")
e("ec_E0_HER", -0.8277, "V vs SHE", -0.9, -0.75, 0.005, cat="electrochem", src="[SRC-EC2] 2H2O + 2e- = H2 + 2OH-", status="unverified", desc="Standard potential of HER in alkaline medium (a_OH=1, p_H2=1 atm)")
e("ec_alpha_a", 0.8, "-", 0.3, 2.0, None, cat="electrochem", src="[SRC-EC3] placeholder", dist="norm", sd=0.2, desc="Anodic apparent transfer coefficient (x electrons) of Al dissolution")
e("ec_alpha_a_back", 1.0, "-", 0.3, 3.0, None, cat="electrochem", src="[SRC-EC3] placeholder", desc="Backward (Al deposition) transfer coefficient")
e("ec_alpha_c", 0.5, "-", 0.2, 1.0, None, cat="electrochem", src="[SRC-EC4] placeholder", dist="norm", sd=0.1, desc="Cathodic transfer coefficient of HER on Al")
e("ec_alpha_c_back", 0.5, "-", 0.2, 1.0, None, cat="electrochem", src="[SRC-EC4] placeholder", desc="Backward (H2 oxidation) transfer coefficient")
e("ec_i0a", 3.0e-5, "A m-2", 1e-9, 1e-1, None, cat="electrochem", src="[SRC-EC5] placeholder; default is DERIVED from k25/Ea/n_oh unless set", dist="logn", sd=1.5, desc="Al dissolution exchange current density at 25 C, a_OH=1")
e("ec_i0c", 1.0e-7, "A m-2", 1e-11, 1e-3, None, cat="electrochem", src="[SRC-EC6] placeholder; default is DERIVED from k25/Ea/n_oh unless set", dist="logn", sd=1.5, desc="HER exchange current density on Al at 25 C, a_OH=1")
e("ec_Ea_a", 90.0e3, "J mol-1", 20e3, 150e3, None, cat="electrochem", src="[SRC-EC7] placeholder; default DERIVED unless set", desc="Activation energy of i0a")
e("ec_Ea_c", 90.0e3, "J mol-1", 20e3, 150e3, None, cat="electrochem", src="[SRC-EC7] placeholder; default DERIVED unless set", desc="Activation energy of i0c")
e("ec_gamma_a", 1.0, "-", 0.0, 4.0, None, cat="electrochem", src="[SRC-EC8] placeholder", desc="Order of i0a in a_OH")
e("ec_gamma_c", 0.5, "-", 0.0, 2.0, None, cat="electrochem", src="[SRC-EC8] placeholder; default DERIVED unless set", desc="Order of i0c in a_OH")
e("ec_aAl_floor", 0.01, "mol kg-1", 1e-6, 1.0, None, cat="electrochem", src="[SRC-EC9] placeholder", desc="Minimum aluminate activity at the corroding surface in the Nernst term")
e("ec_use_activities", 1.0, "-", 0.0, 1.0, None, cat="electrochem", src="switch: 1 = Pitzer activities, 0 = ideal (a=c)", status="exact")
e("ec_k_pass", 1.0e-3, "s-1", 1e-5, 1e-1, None, cat="electrochem", src="[SRC-EC10] placeholder", dist="logn", sd=1.0, desc="Oxide re-formation (passivation) rate constant on bare Al")
e("ec_k_diss", 1.0e-2, "s-1", 1e-4, 1.0, None, cat="electrochem", src="[SRC-EC11] placeholder", dist="logn", sd=1.0, desc="Oxide chemical dissolution rate constant at a_OH=1, 25 C")
e("ec_k_diss_order", 1.0, "-", 0.0, 3.0, None, cat="electrochem", src="[SRC-EC11] placeholder", desc="Order of oxide dissolution in a_OH")
e("ec_Ea_diss", 40.0e3, "J mol-1", 10e3, 100e3, None, cat="electrochem", src="[SRC-EC11] placeholder", desc="Activation energy of oxide dissolution")
e("ec_i_passive", 1.0e-2, "A m-2", 0.0, 1.0, None, cat="electrochem", src="[SRC-EC12] placeholder", desc="Residual passive-film dissolution current density")
e("ec_galv_ratio", 0.0, "-", 0.0, 10.0, None, cat="electrochem", src="toggle: noble-metal area per Al area (0 = off)", status="exact", desc="Galvanic coupling: area ratio of intentionally contacted noble metal (Cu/Ni)")
e("ec_i0c_noble", 1.0e-3, "A m-2", 1e-8, 1.0, None, cat="electrochem", src="[SRC-EC13] placeholder", desc="HER exchange current density on the noble metal at 25 C")
e("ec_dE0_dT_Al", 0.0, "V K-1", -1e-2, 1e-2, None, cat="electrochem", src="[SRC-EC14] unknown: 0 = ignored", desc="Temperature coefficient of E0(Al)")
e("ec_dE0_dT_HER", 0.0, "V K-1", -1e-2, 1e-2, None, cat="electrochem", src="[SRC-EC14] unknown: 0 = ignored", desc="Temperature coefficient of E0(HER)")
