e("D_oh_25", 5.27e-9, "m2 s-1", 3e-9, 8e-9, None, cat="transport", src="[SRC-T2] OH- infinite-dilution diffusivity", status="unverified", desc="OH- diffusion coefficient at 25 C (dilute)")
e("sh_min", 2.0, "-", 0.5, 4.0, None, cat="transport", src="diffusion to a sphere in stagnant fluid", status="exact")
e("sh_ak_coeff", 0.52, "-", 0.2, 1.0, None, cat="transport", src="[SRC-T3] Armenante-Kirwan suspended-particle correlation", status="unverified")
e("sh_ak_exp", 0.52, "-", 0.3, 0.8, None, cat="transport", src="[SRC-T3] Armenante-Kirwan suspended-particle correlation", status="unverified")
e("eps_stirred", 0.2, "W kg-1", 0.0, 5.0, None, cat="transport", src="[SRC-T4] stirrer specific power: placeholder", desc="Energy dissipation rate when stirred")
e("jg_tau", 1.0, "s", 0.1, 30.0, None, cat="numerics", src="numerical: low-pass time constant of superficial gas velocity")
e("bub_N_site", 1.0e6, "m-2", 1e3, 1e9, None, cat="bubbles", src="[SRC-B1] nucleation site density", dist="logn", sd=1.0, desc="Active nucleation sites per Al surface area")
e("bub_R_crit", 2.0e-5, "m", 1e-6, 1e-4, None, cat="bubbles", src="[SRC-B2] radius at which a nucleus becomes a growing bubble")
e("bub_contact_angle", 45.0, "deg", 5.0, 90.0, None, cat="bubbles", src="[SRC-B3] Fritz departure angle", dist="norm", sd=15.0, desc="Contact angle for bubble departure")
e("bub_fd0", 0.5, "s-1", 0.01, 20.0, None, cat="bubbles", src="[SRC-B4] detachment frequency of departure-sized bubbles", dist="logn", sd=1.0)
e("bub_coal_k", 1.0, "s-1", 0.0, 20.0, None, cat="bubbles", src="[SRC-B5] coalescence rate coefficient", desc="Coalescence rate scale")
e("bub_theta_max", 0.9, "-", 0.5, 0.95, None, cat="bubbles", src="hexagonal packing limit (0.9069)", status="exact")
e("bub_N_scale", 1.0e4, "m-2", None, None, None, cat="numerics", src="numerical state scaling", status="exact")
e("bub_V_scale", 1.0e-6, "m3 m-2", None, None, None, cat="numerics", src="numerical state scaling", status="exact")
e("precip_layer_thickness", 5.0e-6, "m", 1e-7, 1e-4, None, cat="bubbles", src="[SRC-B6] precipitate layer that fully blocks the surface")
e("precip_theta_max", 0.95, "-", 0.5, 1.0, None, cat="bubbles", src="numerical cap", status="exact")
e("gas_molar_volume_ref", 0.024465, "m3 mol-1", None, None, None, cat="gas", src="ideal gas at 298.15 K, 1 atm", status="exact")
