e("rho_air", 1.2, "kg m-3", 1.0, 1.3, None, cat="scaleup", src="[SRC-U1] air density near 20 C", status="unverified")
e("atv_mass_kg", 350.0, "kg", 200.0, 600.0, None, cat="scaleup", src="[SRC-U2] placeholder: ATV + rider, user-set")
e("atv_CdA", 0.72, "m2", 0.4, 1.2, None, cat="scaleup", src="[SRC-U3] placeholder: drag area")
e("atv_crr", 0.04, "-", 0.015, 0.1, None, cat="scaleup", src="[SRC-U4] placeholder: rolling resistance (off-road)")
e("atv_eta_drive", 0.85, "-", 0.6, 0.95, None, cat="scaleup", src="[SRC-U5] motor+controller+drivetrain efficiency")
e("atv_aux_W", 50.0, "W", 0.0, 500.0, None, cat="scaleup", src="[SRC-U6] auxiliaries (pumps, fans, controls)")
e("al_yield", 0.95, "-", 0.5, 1.0, None, cat="scaleup", src="[SRC-U7] fraction of loaded Al that reacts per charge")
e("naoh_excess", 1.3, "-", 1.0, 3.0, None, cat="scaleup", src="[SRC-U8] NaOH stoichiometric excess in the charge")
e("liquor_aluminate_margin", 0.8, "-", 0.3, 1.0, None, cat="scaleup", src="[SRC-U9] end-of-charge aluminate as a fraction of saturation (precipitation margin)")
e("al_bulk_packing", 0.3, "-", 0.05, 0.6, None, cat="scaleup", src="[SRC-U10] bulk packing of the Al charge (foil/powder/cans)")
e("headspace_fraction", 0.3, "-", 0.1, 0.6, None, cat="scaleup", src="[SRC-U11] reactor free volume fraction (gas/foam)")
e("reactor_wall_mass_per_L", 0.12, "kg L-1", 0.03, 0.5, None, cat="scaleup", src="[SRC-U12] vessel mass per litre of volume (HDPE/steel)")
e("stack_mass_per_cell", 0.15, "kg", 0.05, 0.5, None, cat="scaleup", src="[SRC-U13] 5x5 cm cell incl. plates")
e("bop_mass_fraction", 0.3, "-", 0.0, 1.0, None, cat="scaleup", src="[SRC-U14] balance-of-plant mass as a fraction of reactor+stack mass")
e("cooling_dT_K", 30.0, "K", 10.0, 60.0, None, cat="scaleup", src="[SRC-U15] design reactor-to-ambient temperature difference")
e("cooling_h_eff", 30.0, "W m-2 K-1", 5.0, 200.0, None, cat="scaleup", src="[SRC-U16] effective air-side coefficient of the finned heat exchanger (area-weighted)")
e("batt_Wh_per_kg", 150.0, "Wh kg-1", 80.0, 260.0, None, cat="scaleup", src="[SRC-U17] pack-level specific energy (Li-ion)")
e("batt_Wh_per_L", 300.0, "Wh L-1", 150.0, 600.0, None, cat="scaleup", src="[SRC-U17] pack-level energy density")
e("batt_dod", 0.9, "-", 0.5, 1.0, None, cat="scaleup", src="[SRC-U18] usable depth of discharge")
e("batt_eta_rt", 0.9, "-", 0.7, 0.98, None, cat="scaleup", src="[SRC-U19] battery+charger round trip to wheels")
e("petrol_kWh_per_L", 8.9, "kWh L-1", 8.0, 9.5, None, cat="scaleup", src="[SRC-U20] petrol LHV", status="unverified")
e("petrol_kg_per_L", 0.745, "kg L-1", 0.7, 0.78, None, cat="scaleup", src="[SRC-U20]", status="unverified")
e("petrol_eta", 0.2, "-", 0.12, 0.3, None, cat="scaleup", src="[SRC-U21] small-engine ATV tank-to-wheel efficiency")
e("petrol_tank_mass_factor", 0.15, "kg kg-1", 0.05, 0.4, None, cat="scaleup", src="[SRC-U22] tank mass per kg fuel")
e("refill_minutes", 10.0, "min", 1.0, 120.0, None, cat="scaleup", src="[SRC-U23] time to swap a charge cartridge")
# ---- LCA factors (screening, placeholders: replace with your inventory data)
e("ef_al_primary", 16.5, "kgCO2e kg-1", 6.0, 30.0, None, cat="lca", src="[SRC-L1] primary aluminium, global-average-type value (placeholder; grid dependent)")
e("ef_al_recycled", 0.6, "kgCO2e kg-1", 0.2, 2.0, None, cat="lca", src="[SRC-L2] remelted scrap (placeholder)")
e("ef_naoh", 1.2, "kgCO2e kg-1", 0.5, 3.0, None, cat="lca", src="[SRC-L3] chlor-alkali NaOH (placeholder)")
e("ef_water", 0.0003, "kgCO2e kg-1", 0.0, 0.01, None, cat="lca", src="[SRC-L4] tap water")
e("ef_gibbsite_credit", 0.5, "kgCO2e kg-1", 0.0, 3.0, None, cat="lca", src="[SRC-L5] avoided impact per kg of reusable Al(OH)3/aluminate (placeholder)")
e("ef_petrol_wtw", 2.9, "kgCO2e L-1", 2.3, 3.5, None, cat="lca", src="[SRC-L6] well-to-wheel petrol (placeholder)")
e("ef_grid", 0.75, "kgCO2e kWh-1", 0.0, 1.2, None, cat="lca", src="[SRC-L7] USER-SET grid emission factor (placeholder, India-like order of magnitude)")
e("lca_charge_eff", 0.88, "-", 0.7, 0.98, None, cat="lca", src="[SRC-L8] grid-to-battery charging efficiency")
e("liquor_max_molality", 6.0, "mol kg-1", 2.0, 12.0, None, cat="scaleup", src="[SRC-U24] practical maximum NaOH molality of the charge (viscosity, handling, Pitzer validity)")
