for key, v, unit in (("hf", 0.0, "J mol-1"), ("gf", 0.0, "J mol-1"), ("s0", 205.15, "J mol-1 K-1"), ("cp", 29.36, "J mol-1 K-1")):
    e(f"{key}:O2(g)", v, unit, None, None, abs(v) * 0.01 + 1.0, cat="species", src="NBS-type [SRC-S-O2]", status="unverified", desc=f"{key} of O2(g)")
e("lhv_h2", 241.8e3, "J mol-1", 240e3, 243e3, 200.0, cat="species", src="[SRC-S-H2] lower heating value", status="unverified")
e("hhv_h2", 285.83e3, "J mol-1", 284e3, 287e3, 200.0, cat="species", src="[SRC-S-H2] higher heating value", status="unverified")
# ---- AEM cell (SI; area basis = geometric electrode area)
e("fc_i0_hor", 50.0, "A m-2", 1.0, 2.0e2, None, cat="fuelcell", src="[SRC-F1] NiMo HOR exchange current density (prototype prior 5 mA/cm2)", dist="logn", sd=0.8)
e("fc_alpha_hor", 0.5, "-", 0.3, 1.0, None, cat="fuelcell", src="[SRC-F2] anodic transfer coefficient of HOR")
e("fc_beta_hor", 0.5, "-", 0.3, 1.0, None, cat="fuelcell", src="[SRC-F2] cathodic (backward) transfer coefficient of HOR")
e("fc_i0_orr", 1.0, "A m-2", 1e-2, 1e1, None, cat="fuelcell", src="[SRC-F3] Ag ORR exchange current density (prior 0.1 mA/cm2)", dist="logn", sd=0.8)
e("fc_alpha_orr", 0.8, "-", 0.4, 1.2, None, cat="fuelcell", src="[SRC-F4] cathodic transfer coefficient of ORR")
e("fc_beta_orr", 0.5, "-", 0.2, 1.0, None, cat="fuelcell", src="[SRC-F4] backward transfer coefficient of ORR")
e("fc_order_h2", 0.5, "-", 0.0, 1.0, None, cat="fuelcell", src="[SRC-F5] reaction order of HOR in pH2")
e("fc_order_o2", 0.5, "-", 0.0, 1.0, None, cat="fuelcell", src="[SRC-F5] reaction order of ORR in pO2")
e("fc_Ea_hor", 30.0e3, "J mol-1", 10e3, 80e3, None, cat="fuelcell", src="[SRC-F6] placeholder")
e("fc_Ea_orr", 40.0e3, "J mol-1", 10e3, 80e3, None, cat="fuelcell", src="[SRC-F6] placeholder")
e("fc_asr", 3.0e-5, "ohm m2", 1e-5, 8e-5, None, cat="fuelcell", src="[SRC-F7] homemade AEM ASR at reference T, lambda (prior 0.3 ohm cm2)", dist="logn", sd=0.3)
e("fc_Ea_asr", 15.0e3, "J mol-1", 5e3, 40e3, None, cat="fuelcell", src="[SRC-F8] placeholder")
e("fc_T_ref", 323.15, "K", None, None, None, cat="fuelcell", src="reference temperature of ASR and exchange currents", status="exact")
e("fc_lambda_ref", 12.0, "-", 4.0, 25.0, None, cat="fuelcell", src="[SRC-F9] reference membrane water content for ASR")
e("fc_lambda_exp", 1.0, "-", 0.0, 3.0, None, cat="fuelcell", src="[SRC-F9] conductivity exponent sigma ~ lambda^m")
e("fc_lambda_max", 25.0, "-", 10.0, 40.0, None, cat="fuelcell", src="[SRC-F9] fully hydrated water content")
e("fc_lambda_dry", 4.0, "-", 1.0, 8.0, None, cat="fuelcell", src="[SRC-F9] dry-out threshold")
e("fc_lambda_flood", 20.0, "-", 12.0, 30.0, None, cat="fuelcell", src="[SRC-F9] flooding onset")
e("fc_sorption_b", 1.0, "-", 0.3, 3.0, None, cat="fuelcell", src="[SRC-F10] sorption isotherm exponent")
e("fc_ion_density", 0.08, "mol m-2", 0.01, 0.5, None, cat="fuelcell", src="[SRC-F11] ionic groups per electrode area (IEC*rho*t)")
e("fc_k_evap_c", 0.01, "m s-1", 1e-4, 0.1, None, cat="fuelcell", src="[SRC-F12] cathode-side evaporation mass transfer coefficient")
e("fc_k_evap_a", 0.002, "m s-1", 1e-5, 0.05, None, cat="fuelcell", src="[SRC-F12] anode-side evaporation mass transfer coefficient")
e("fc_RH_air", 0.5, "-", 0.0, 1.0, None, cat="fuelcell", src="cathode air relative humidity", status="exact")
e("fc_iL", 6000.0, "A m-2", 1000.0, 2.0e4, None, cat="fuelcell", src="[SRC-F13] limiting current density (prior 0.6 A/cm2)")
e("fc_conc_factor", 1.0, "-", 0.2, 3.0, None, cat="fuelcell", src="[SRC-F14] concentration-loss scaling")
e("fc_flood_iL_penalty", 0.5, "-", 0.0, 0.9, None, cat="fuelcell", src="[SRC-F15] max iL reduction when flooded")
e("fc_T_stack", 323.15, "K", 298.15, 343.15, None, cat="fuelcell", src="operating choice", desc="Stack operating temperature (held constant unless thermal model on)")
e("fc_P_cathode", 1.0, "atm", 1.0, 2.0, None, cat="fuelcell", src="operating choice: air pressure", status="exact")
e("fc_x_o2", 0.21, "-", None, None, None, cat="fuelcell", src="dry air O2 fraction", status="exact")
e("fc_co2_ppm", 420.0, "ppm", 0.0, 2000.0, None, cat="fuelcell", src="[SRC-F16] ambient CO2", status="unverified")
e("fc_carb_on", 0.0, "-", 0.0, 1.0, None, cat="fuelcell", src="switch: membrane carbonation model (off: unconstrained parameters)", status="exact")
e("fc_k_carb", 1.0e-3, "s-1 atm-1", 0.0, 1.0, None, cat="fuelcell", src="[SRC-F17] placeholder carbonation rate per atm CO2")
e("fc_k_regen", 1.0e-4, "m2 A-1 s-1", 0.0, 1e-2, None, cat="fuelcell", src="[SRC-F17] placeholder self-purging rate per current density")
e("fc_sigma_carb_ratio", 0.3, "-", 0.1, 1.0, None, cat="fuelcell", src="[SRC-F18] carbonate/hydroxide conductivity ratio")
e("fc_k_cat", 0.0, "h-1", 0.0, 0.1, None, cat="fuelcell", src="[SRC-F19] catalyst decay rate (0 = off, unconstrained)")
e("fc_k_mem", 0.0, "h-1", 0.0, 0.1, None, cat="fuelcell", src="[SRC-F19] membrane resistance growth rate (0 = off, unconstrained)")
e("fc_asr_spread", 0.05, "-", 0.0, 0.3, None, cat="fuelcell", src="[SRC-F20] cell-to-cell relative ASR spread (1 sigma)")
e("fc_cell_C", 150.0, "J K-1", 20.0, 1000.0, None, cat="fuelcell", src="[SRC-F21] heat capacity per cell")
e("fc_UA_cell", 0.15, "W K-1", 0.01, 2.0, None, cat="fuelcell", src="[SRC-F21] cell-to-ambient conductance")
e("fc_k_cc", 0.5, "W K-1", 0.0, 5.0, None, cat="fuelcell", src="[SRC-F21] neighbouring-cell thermal conductance")
e("fc_thermal_on", 0.0, "-", 0.0, 1.0, None, cat="fuelcell", src="switch: stack thermal model (0 = T held at fc_T_stack)", status="exact")
e("fc_utilization", 1.0, "-", 0.5, 1.0, None, cat="fuelcell", src="H2 utilisation (dead-ended anode + purge)", status="exact")
# ---- flow field / nickel foam
e("ff_n_channels", 10.0, "-", 1.0, 100.0, None, cat="fuelcell", src="plate design")
e("ff_ch_width", 1.0e-3, "m", 1e-4, 5e-3, None, cat="fuelcell", src="plate design")
e("ff_ch_depth", 1.0e-3, "m", 1e-4, 5e-3, None, cat="fuelcell", src="plate design")
e("ff_ch_length", 0.05, "m", 0.01, 0.2, None, cat="fuelcell", src="plate design")
e("ff_header_k", 0.05, "-", 0.0, 1.0, None, cat="fuelcell", src="[SRC-F22] header segment resistance as a fraction of a channel resistance")
e("foam_porosity", 0.95, "-", 0.8, 0.98, None, cat="fuelcell", src="[SRC-F23] nickel foam porosity")
e("foam_pore_d", 5.0e-4, "m", 1e-4, 2e-3, None, cat="fuelcell", src="[SRC-F23] nickel foam pore diameter")
e("foam_forchheimer", 0.55, "-", 0.1, 1.0, None, cat="fuelcell", src="[SRC-F24] form-drag coefficient")
e("foam_thickness", 1.5e-3, "m", 5e-4, 5e-3, None, cat="fuelcell", src="[SRC-F23] nickel foam thickness")
e("mu_h2", 8.9e-6, "Pa s", None, None, None, cat="fuelcell", src="[SRC-F25] H2 viscosity near 300 K", status="unverified")
e("rho_h2_stp", 0.0899, "kg m-3", None, None, None, cat="fuelcell", src="H2 density at 273.15 K, 1 atm", status="unverified")
# ---- BOP
e("dcdc_P0", 0.05, "W", 0.0, 5.0, None, cat="system", src="[SRC-S3] DC/DC fixed loss")
e("dcdc_a", 0.03, "-", 0.0, 0.2, None, cat="system", src="[SRC-S3] DC/DC proportional loss")
e("dcdc_b", 1.0e-4, "W-1", 0.0, 1e-2, None, cat="system", src="[SRC-S3] DC/DC quadratic loss")
e("cond_T", 298.15, "K", 273.15, 330.0, None, cat="system", src="condenser/dryer outlet temperature", status="exact")
e("cond_mist_eff", 0.99, "-", 0.5, 0.9999, None, cat="system", src="[SRC-S4] mist filter efficiency")
e("mist_g_per_mol_boil", 0.05, "g mol-1", 0.0, 5.0, None, cat="system", src="[SRC-S5] NaOH mist carried per mol of boiled water")
e("dryer_dew_K", 263.15, "K", 233.15, 298.15, None, cat="system", src="dryer outlet dew point (if dryer on)", status="exact")
e("batt_eta_chg", 0.97, "-", 0.8, 1.0, None, cat="system", src="[SRC-S6] battery charge efficiency")
e("batt_eta_dis", 0.97, "-", 0.8, 1.0, None, cat="system", src="[SRC-S6] battery discharge efficiency")
e("sys_dt", 5.0, "s", 0.5, 60.0, None, cat="numerics", src="system coupling step", status="exact")
e("fc_UA_end_mult", 2.5, "-", 1.0, 10.0, None, cat="fuelcell", src="[SRC-F21] end plates lose more heat than inner cells")
e("ec_eps_al", 0.1, "-", 0.0, 1.0, None, cat="electrochem", src="[SRC-EC15] exponent of the aluminate (Nernst) factor in the reduced echem model (= alpha_a alpha_c/(3(alpha_a+alpha_c)) in the full model)")
